# This is a basic workflow to help you get started with Actions

name: Python OSM training automation 

# Controls when the workflow will run
on:
  #schedule:
   #- cron:  '40 */1 * * *'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: install papckages
        run: pip install playwright

      - name: more
        run: playwright install chromium
      
      

      # Runs a set of commands using the runners shell
      
      - name: Run the second task
        run: python .github/workflows/coins.py
      #- name: Run a multi-line script
       # run: python .github/workflows/train.py
      - name: Run the second task 2
        run: python .github/workflows/coins.py
      #- name: Run a multi-line script 2
       # run: python .github/workflows/train.py
      
